
services:
  - type: web
    name: svg-to-tgs-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_PATH
        value: bot_database.db
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
    autoDeploy: true
    disk:
      name: sqlite-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
