
services:
  - type: web
    name: svg-to-tgs-bot
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libcairo2-dev libpango1.0-dev libgdk-pixbuf2.0-dev libffi-dev shared-mime-info
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_PATH
        value: /opt/render/project/src/bot_database.db
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PYTHONPATH
        value: /opt/render/project/src
    autoDeploy: true
    disk:
      name: sqlite-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
